I'm sorry, but an uncaught exception occurred.

While loading <'Image' u'F4_triste.png'>:
  File "game/label_01rencontre.rpy", line 18, in script
    r   "C'est l'heure... Je dois y..."
  File "game/label_01rencontre.rpy", line 18, in script
    r   "C'est l'heure... Je dois y..."
IOError: Couldn't find file 'F4_triste.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "game/label_01rencontre.rpy", line 18, in script
    r   "C'est l'heure... Je dois y..."
  File "game/label_01rencontre.rpy", line 18, in script
    r   "C'est l'heure... Je dois y..."
  File "renpy/ast.py", line 715, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1384, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1179, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 851, in do_display
    **display_args)
  File "renpy/character.py", line 601, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3007, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3517, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "renpy/display/core.py", line 2377, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 492, in renpy.display.render.render_screen
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 751, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 751, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/layout.py", line 751, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/transform.py", line 927, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 116, in renpy.display.accelerator.transform_render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/image.py", line 501, in render
    return wrap_render(self.target, width, height, st, at)
  File "renpy/display/image.py", line 307, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "renpy/display/im.py", line 607, in render
    return cache.get(self, render=True)
  File "renpy/display/im.py", line 271, in get
    surf = image.load()
  File "renpy/display/im.py", line 651, in load
    filelike = renpy.loader.load(self.filename)
  File "renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'F4_triste.png'.

Windows-10-10.0.18362
Ren'Py 7.4.2.1292
Robot et humain 1.0
Thu Feb 18 11:13:35 2021
